const I={
  scenarios:{hospital:{name:'If I were hospitalized tonight',short:'Hospital tonight',icon:'✚',desc:'Could someone find the essentials and keep things moving?',domains:['Emergency','Insurance','Money & Bills','Loved Ones']},household:{name:"If I couldn’t manage my household",short:'Household handoff',icon:'⌂',desc:'Could someone handle bills, home care, and daily responsibilities?',domains:['Money & Bills','Home','Digital Life','Loved Ones']},leave:{name:'If I had to leave home unexpectedly',short:'Leave unexpectedly',icon:'↗',desc:'Could someone locate what matters and care for home and loved ones?',domains:['Emergency','Documents','Home','Loved Ones']},death:{name:'If I died',short:'After a death',icon:'◇',desc:'Would the right people know where to begin?',domains:['Documents','Insurance','Money & Bills','Digital Life','Loved Ones']}},
  domains:['Emergency','Documents','Insurance','Money & Bills','Home','Digital Life','Loved Ones'],
  strings:{promise:'Be prepared for the moments when someone else may need to step in.'}
};
const KEY='bePrepared.v0.1';
const blank=()=>({version:'0.1',createdAt:new Date().toISOString(),people:[{id:'me',name:'Me',relationship:'Self',trustedContacts:[],futurePreparedId:null,sponsor:null,provider:null}],items:[],preparednessConfirmations:[],events:[],feedback:null,settings:{overdueMonths:6}});
let state=load(),route='home',scenario='hospital',activePerson='me',checkQueue=[],checkIndex=0;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||blank()}catch{return blank()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function event(name,data={}){state.events.push({name,at:new Date().toISOString(),...data});save()}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function ago(date){if(!date)return 999;return Math.floor((Date.now()-new Date(date))/(864e5*30.44))}
function person(id){return state.people.find(p=>p.id===id)}
function itemScore(x){let critical=x.critical?1.2:1;let exist=x.exists==='yes'?20:0,loc=x.location?.trim()?25:0,handler=x.handler?.trim()?15:0,knows=x.whoKnows?.trim()?25:0,rec=x.lastConfirmed?(ago(x.lastConfirmed)<=x.overdueMonths?15:ago(x.lastConfirmed)<=x.overdueMonths*2?7:0):0;return Math.round((exist+loc+handler+knows+rec)*critical)}
function score(pid,sid){let items=relevant(pid,sid);if(!items.length)return 0;let total=items.reduce((a,x)=>a+itemScore(x),0),max=items.reduce((a,x)=>a+(x.critical?120:100),0);let critical=items.filter(x=>x.critical);if(critical.some(x=>!x.location||!x.whoKnows))total*=.82;return Math.min(100,Math.round(total/max*100))}
function overall(pid){let vals=Object.keys(I.scenarios).map(s=>score(pid,s));return Math.round(vals.reduce((a,b)=>a+b,0)/vals.length)}
function status(n){return n>=75?['Ready','ready']:n>=40?['Needs attention','attention']:['Not ready','notready']}
function initials(n){return n.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function shell(content){return `<div class="shell"><div class="print-only privacy-print">Be Prepared · Preparedness locations only · No passwords, account numbers, medical details, or documents</div>${content}</div>`}
function scenarioView(){let p=person(activePerson),s=I.scenarios[scenario],n=score(p.id,scenario),st=status(n),items=relevant(p.id,scenario),gaps=items.filter(x=>itemScore(x)<75).sort((a,b)=>itemScore(a)-itemScore(b));return `<div class="page-head"><div><div class="eyebrow">${esc(p.name)} · Scenario</div><h1>${s.name}</h1><p class="lead">${s.desc}</p></div><div><span class="big-score">${n}%</span><div class="status ${st[1]}">${st[0]}</div></div></div><div class="hero-actions"><button class="btn primary" data-action="add-item">Add preparedness item</button><button class="btn" data-go="handoff">Run handoff test</button></div><div class="section-head"><div><h2>Top gaps</h2><p>Fix these first to make a handoff possible.</p></div></div><section class="card">${gaps.length?gaps.slice(0,4).map(x=>`<div class="gap-row"><span class="status ${x.critical?'notready':'attention'}">${x.critical?'Critical':'Gap'}</span><div><b>${esc(x.title)}</b><div class="muted tiny">${!x.location?'Add where it can be found':!x.whoKnows?'Choose who else knows':ago(x.lastConfirmed)>x.overdueMonths?'Confirm it is still correct':'Complete the 5Q check'}</div></div><button class="btn small" data-edit="${x.id}">Fix</button></div>`).join(''):'<p class="muted">No items yet. Add only the directions someone would need — never the sensitive contents.</p>'}</section><div class="section-head"><div><h2>Preparedness map</h2><p>Seven domains, filtered for this situation.</p></div></div><div class="domain-grid">${I.domains.map(d=>{let list=items.filter(x=>x.domain===d);return `<section class="domain-card"><header><h3>${d}</h3><span class="muted tiny">${list.length} item(s)</span></header>${list.map(x=>`<div class="item-row"><div><b>${esc(x.title)}</b><div class="muted tiny">${x.location?esc(x.location):'Location missing'}</div></div>${ago(x.lastConfirmed)>x.overdueMonths?'<span class="overdue">Overdue</span>':''}<button data-edit="${x.id}">Edit</button></div>`).join('')||'<p class="muted tiny">Nothing mapped for this scenario.</p>'}</section>`}).join('')}</div>`}
function handoffView(){let p=person(activePerson)||state.people[0],contact=p.trustedContacts?.[0]||'',n=score(p.id,scenario),items=relevant(p.id,scenario),yes=items.filter(x=>x.location&&x.whoKnows&&itemScore(x)>=65),no=items.filter(x=>!yes.includes(x));return `<div class="page-head"><div><div class="eyebrow">Handoff test</div><h1>Could someone step in today?</h1><p class="lead">Test a specific person and situation. This is a practical check, not a legal or medical assessment.</p></div></div><section class="card"><div class="handoff-controls"><select id="handoffPerson">${state.people.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>Plan for: ${esc(x.name)}</option>`)}</select><select id="handoffScenario">${Object.entries(I.scenarios).map(([id,x])=>`<option value="${id}" ${id===scenario?'selected':''}>${x.short}</option>`)}</select><input id="handoffContact" value="${esc(contact)}" placeholder="Who would step in?" aria-label="Handoff contact"><button class="btn primary" data-action="run-handoff">Run test</button></div><div class="section-head"><div><h2>${I.scenarios[scenario].short} — ${contact?esc(contact):'your contact'} handoff readiness</h2></div><div class="big-score">${n}%</div></div><div class="split"><div><h3>Could find</h3><ul class="result-list">${yes.map(x=>`<li class="yes">✓ ${esc(x.title)} <span class="muted">— ${esc(x.location)}</span></li>`).join('')||'<li class="muted">Nothing is handoff-ready yet.</li>'}</ul></div><div><h3>Wouldn’t know</h3><ul class="result-list">${no.map(x=>`<li class="no">× ${esc(x.title)} <span class="muted">— ${!x.location?'location missing':!x.whoKnows?'no one else knows':'needs confirmation'}</span></li>`).join('')||'<li class="muted">No known gaps.</li>'}</ul></div></div></section>`}
function overdueItems(){return state.items.filter(x=>ago(x.lastConfirmed)>x.overdueMonths).sort((a,b)=>ago(b.lastConfirmed)-ago(a.lastConfirmed))}
function checkupView(){let od=overdueItems();return `<div class="page-head"><div><div class="eyebrow">5-minute check-up</div><h1>Keep directions current.</h1><p class="lead">A small confirmation is more useful than a forgotten, complete-looking plan.</p></div></div><section class="card check-card"><h2>${od.length} item${od.length===1?'':'s'} to confirm</h2><p class="muted">Items become due after their 6- or 12-month review interval.</p>${od.slice(0,5).map(x=>`<div class="item-row"><div><b>${esc(x.title)}</b><div class="muted tiny">${esc(person(x.personId)?.name)} · ${x.lastConfirmed?'Last confirmed '+new Date(x.lastConfirmed).toLocaleDateString():'Never confirmed'}</div></div><span class="overdue">${x.overdueMonths} mo.</span></div>`).join('')}<div class="hero-actions"><button class="btn primary" data-action="start-checkup" ${!od.length?'disabled':''}>Start check-up</button></div></section>`}
function searchView(){let q=window.searchTerm||'',items=state.items.filter(x=>!q||`${x.title} ${x.location} ${x.handler} ${x.whoKnows}`.toLowerCase().includes(q.toLowerCase()));return `<div class="page-head"><div><div class="eyebrow">Where Is It?</div><h1>Find the direction, not the secret.</h1><p class="lead">Search safe location hints and contact names across every preparedness map.</p></div></div><input class="searchbox" id="searchInput" value="${esc(q)}" placeholder="Try “insurance”, “desk drawer”, or a contact name…" autofocus><section class="card">${items.map(x=>`<div class="item-row"><div><b>${esc(x.title)}</b><div class="muted tiny">${esc(person(x.personId)?.name)} · ${esc(x.domain)}</div></div><span>${esc(x.location||'Location missing')}</span><button data-edit="${x.id}">Edit</button></div>`).join('')||'<p class="muted">No matching directions found.</p>'}</section>`}
function emergencyView(){let items=state.items.filter(x=>x.domain==='Emergency'||x.scenarioFlags?.includes('leave'));return `<div class="page-head"><div><div class="eyebrow">Emergency view</div><h1>Only what helps someone act.</h1><p class="lead">Locations and contact people only. No passwords, account numbers, medical details, or document contents.</p></div><button class="btn" data-action="print">Print / Save PDF</button></div><div class="notice">For immediate danger in the US, call 911. Be Prepared does not provide emergency, medical, or legal advice.</div><section class="card">${items.map(x=>`<div class="item-row"><div><b>${esc(x.title)}</b><div class="muted tiny">${esc(person(x.personId)?.name)} · ${esc(x.domain)}</div></div><span><b>Where:</b> ${esc(x.location||'Not mapped')}<br><span class="tiny muted"><b>Contact:</b> ${esc(x.handler||x.whoKnows||'Not mapped')}</span></span></div>`).join('')||'<p class="muted">No emergency directions have been mapped yet.</p>'}</section>`}
function feedbackView(){return `<div class="page-head"><div><div class="eyebrow">Feedback & future</div><h1>Should continuity continue beyond this device?</h1><p class="lead">A future paid service could add trusted contacts, reminders, a Prepared ID, and controlled handoff. None of these cloud features exist in this prototype.</p></div></div><section class="card"><h2>Would you pay for that Continuity Service?</h2><div class="hero-actions">${['yes','maybe','no'].map(x=>`<button class="btn ${state.feedback===x?'primary':''}" data-intent="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div><p class="muted tiny">Your response stays on this device and is included only if you export your backup.</p></section>`}
function aboutView(){return `<div class="page-head"><div><div class="eyebrow">About & privacy</div><h1>A map for continuity, not a container for secrets.</h1><p class="lead">Be Prepared helps another person know what exists, where to look, who handles it, who else knows, and when that direction was last confirmed.</p></div></div><div class="split"><section class="card"><h2>What Be Prepared is</h2><p class="muted">A local-first preparedness map and practical handoff check for life’s disruptive moments.</p><div class="fiveq">${['Does it exist?','Where is it?','Who handles it?','Who else knows?','Last confirmed?'].map((x,i)=>`<div class="qstep"><b>${i+1}</b>${x}</div>`).join('')}</div><p><b>Completeness ≠ readiness.</b> A detailed item is not ready if the right person could not find or act on it.</p></section><section class="card"><h2>What Be Prepared is NOT</h2><ul class="not-list"><li>Not a password manager</li><li>Not a document vault</li><li>Not a medical record</li><li>Not a legal will service</li><li>Not a bank or insurance database</li></ul></section></div><section class="card" style="margin-top:16px"><h3>Local-only privacy</h3><p class="muted">Data is stored in your browser’s local storage. There is no backend, account, analytics service, email, identity verification, dead-man switch, or external transmission. Clearing browser data can erase your map, so export a backup if you want one.</p></section>`}
function go(r){route=r;render();scrollTo(0,0)}
function action(a){if(a==='load-demo')loadDemo();if(a==='add-person')addPerson();if(a==='add-item')editItem();if(a==='run-handoff'){let c=document.querySelector('#handoffContact').value.trim(),p=person(activePerson);if(c&&!p.trustedContacts.includes(c))p.trustedContacts.push(c);event('handoff_test_run',{personId:activePerson,scenario});render()}if(a==='start-checkup')startCheckup();if(a==='print')window.print();if(a==='export')exportData();if(a==='import')document.querySelector('#importFile').click();if(a==='reset')reset()}
function openModal(html){document.querySelector('#modalBody').innerHTML=html;document.querySelector('#modal').showModal()}
function closeModal(){document.querySelector('#modal').close()}
function removePerson(id){if(confirm(`Remove ${person(id).name} and all of their preparedness items?`)){state.people=state.people.filter(x=>x.id!==id);state.items=state.items.filter(x=>x.personId!==id);save();render()}}
function startCheckup(){checkQueue=overdueItems();checkIndex=0;event('checkup_started',{count:checkQueue.length});showCheck()}
function showCheck(){let x=checkQueue[checkIndex];if(!x){event('checkup_completed',{count:checkQueue.length});closeModal();render();toast('Check-up complete.');return}openModal(`<div class="eyebrow">Item ${checkIndex+1} of ${checkQueue.length}</div><h2>${esc(x.title)}</h2><p><b>Location:</b> ${esc(x.location||'Not mapped')}<br><b>Who knows:</b> ${esc(x.whoKnows||'Not mapped')}</p><p class="muted">Is this direction still correct?</p><div class="check-actions"><button type="button" class="btn primary" id="stillCorrect">Yes, still correct</button><button type="button" class="btn" id="needsUpdate">Needs update</button></div>`);document.querySelector('#stillCorrect').onclick=()=>{x.lastConfirmed=new Date().toISOString();x.preparednessConfirmations=[...(x.preparednessConfirmations||[]),{at:x.lastConfirmed,result:'confirmed'}];save();checkIndex++;showCheck()};document.querySelector('#needsUpdate').onclick=()=>editItem(x.id)}
function exportData(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`be-prepared-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Local backup exported.')}
document.querySelector('#importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let reader=new FileReader();reader.onload=()=>{try{let x=JSON.parse(reader.result);if(!Array.isArray(x.people)||!Array.isArray(x.items))throw Error();if(confirm('Replace current local data with this backup?')){state=x;save();render();toast('Backup imported.')}}catch{toast('That file is not a valid Be Prepared backup.')}};reader.readAsText(f);e.target.value=''};
function reset(){if(confirm('Permanently erase all Be Prepared data stored by this browser?')){localStorage.removeItem(KEY);state=blank();activePerson='me';route='home';render();toast('Local data erased.')}}
function toast(msg){let t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function render(){document.querySelectorAll('[data-go]').forEach(b=>{let on=b.dataset.go===route;b.classList.toggle('active',on);on?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')});let fn={home:homeView,build:buildView,people:peopleView,scenario:scenarioView,handoff:handoffView,checkup:checkupView,search:searchView,emergency:emergencyView,more:moreView,feedback:feedbackView,about:aboutView}[route]||homeView;document.querySelector('#main').innerHTML=shell(fn());bind()}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>{scenario=b.dataset.scenario;route='scenario';render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(b.dataset.action==='load-demo-go'){loadDemo();route='build';render()}else action(b.dataset.action)});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editItem(b.dataset.edit));document.querySelectorAll('[data-person-open]').forEach(b=>b.onclick=()=>{activePerson=b.dataset.personOpen;route='build';render()});document.querySelectorAll('[data-person-edit]').forEach(b=>b.onclick=()=>editPerson(b.dataset.personEdit));document.querySelectorAll('[data-person-delete]').forEach(b=>b.onclick=()=>removePerson(b.dataset.personDelete));document.querySelectorAll('[data-intent]').forEach(b=>b.onclick=()=>{state.feedback=b.dataset.intent;event('saas_intent_'+b.dataset.intent);render()});let hp=document.querySelector('#homePerson');if(hp)hp.onchange=()=>{if(hp.value==='__add')addPerson();else{activePerson=hp.value;render()}};let hi=document.querySelector('#handoffPerson');if(hi)hi.onchange=()=>{activePerson=hi.value;render()};let hs=document.querySelector('#handoffScenario');if(hs)hs.onchange=()=>{scenario=hs.value;render()};let si=document.querySelector('#searchInput');if(si)si.oninput=()=>{window.searchTerm=si.value;render();const next=document.querySelector('#searchInput');if(next){next.focus();next.setSelectionRange(next.value.length,next.value.length)}}}
/* Be Prepared v0.2 clarity update */
const V2_TOPICS=['Contacts & Support','Documents & Legal','Money & Bills','Insurance','Home & Property','Digital Life','Family, Pets & Care'];
const V2_MOVE={Emergency:'Contacts & Support',Documents:'Documents & Legal',Home:'Home & Property','Loved Ones':'Family, Pets & Care'};
I.domains=V2_TOPICS;
I.scenarios={hospital:{name:'Hospital',short:'Hospital',desc:'Could someone keep important things moving?',domains:['Contacts & Support','Insurance','Money & Bills','Family, Pets & Care']},household:{name:'Household',short:'Household',desc:'Could someone manage the household?',domains:['Money & Bills','Home & Property','Digital Life','Family, Pets & Care']},leave:{name:'Leave unexpectedly',short:'Leave unexpectedly',desc:'Could someone find what matters?',domains:['Contacts & Support','Documents & Legal','Home & Property','Family, Pets & Care']},death:{name:'After a death',short:'After a death',desc:'Would the right people know where to begin?',domains:['Documents & Legal','Insurance','Money & Bills','Digital Life','Family, Pets & Care']}};
state.people=(state.people||[]).map((p,i)=>({...p,name:p.id==='me'||(!i&&p.relationship==='Self')?'My map':p.name,relationship:p.id==='me'?'Self':p.relationship}));
state.items=(state.items||[]).map(x=>({...x,domain:V2_MOVE[x.domain]||x.domain,overdueMonths:[3,6,12].includes(+x.overdueMonths)?+x.overdueMonths:12,lastConfirmed:x.lastConfirmed||null}));
function relevant(pid,sid){let ds=I.scenarios[sid].domains;return state.items.filter(x=>x.personId===pid&&ds.includes(x.domain))}
save();
function homeView(){return `<section class="welcome-hero"><div class="welcome-copy"><div class="eyebrow light">Be Prepared · your 5Q map</div><h1>Make important information easy to find.</h1><p class="lead">Use five simple questions to record what exists, where to find it, and who can help.</p><div class="hero-actions"><button class="btn primary" data-go="build">Build my map</button><button class="btn demo-light" data-action="load-demo-go">Load demo</button></div></div><aside class="welcome-trust"><h2>Works without internet.</h2><p>Your map stays in this browser when you close it. Browser data can be cleared, so export a backup or print a PDF when your map is ready.</p><button class="btn" data-go="more">Backup and print options</button></aside></section><section class="privacy-simple"><div class="card"><h2>What to add</h2><p>Add enough information to help someone find the information and contact the right person.</p></div><div class="card"><h2>Keep sensitive details elsewhere</h2><p>Do not add passwords, account numbers, medical records, or document contents. Be Prepared points to them; it does not store them.</p></div></section>`}
function buildView(){let p=person(activePerson)||state.people[0],items=state.items.filter(x=>x.personId===p.id);return `<div class="page-head build-head"><div><div class="eyebrow">Build my map · 5Q</div><h1>${p.id==='me'?'My map':`${esc(p.name)}’s map`}</h1><p class="lead">Choose a topic, then answer five simple questions for each item.</p></div><div class="build-person"><label for="homePerson">Map for</label><select id="homePerson">${state.people.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${esc(x.name)}</option>`).join('')}<option value="__add">+ Add a person</option></select></div></div><div class="map-toolbar"><div><h2>Your topics</h2><p class="muted">${items.length} item${items.length===1?'':'s'} in this map.</p></div><div class="hero-actions"><button class="btn" data-action="load-demo">Load demo</button><button class="btn primary" data-action="add-item">Add an item</button></div></div><div class="domain-overview">${I.domains.map(d=>{let list=items.filter(x=>x.domain===d);return `<section class="domain-mini"><b>${d}</b><span>${list.length?`${list.length} item${list.length===1?'':'s'}`:'Not started'}</span>${list.map(x=>`<button data-edit="${x.id}">${esc(x.title)} →</button>`).join('')}</section>`}).join('')}</div><section class="secondary-section"><div class="section-head"><div><h2>Could someone step in?</h2><p>Test your map against a real situation.</p></div><button class="btn" data-go="handoff">Run a handoff test</button></div></section>`}
function peopleView(){return `<div class="page-head"><div><div class="eyebrow">People</div><h1>Maps for the people you care about</h1><p class="lead">Use a real name and choose your relationship.</p></div><button class="btn primary" data-action="add-person">Add person</button></div><section class="card people-list">${state.people.map(p=>`<details class="person-drop"><summary><span class="avatar">${initials(p.name)}</span><span><b>${esc(p.name)}</b><small>${esc(p.relationship)} · ${overall(p.id)}% ready</small></span><span class="chevron">⌄</span></summary><div class="person-actions"><button class="btn small" data-person-open="${p.id}">Open map</button><button class="btn small" data-person-edit="${p.id}">Edit</button>${p.id!=='me'?`<button class="btn small danger" data-person-delete="${p.id}">Remove</button>`:''}</div></details>`).join('')}</section>`}
function itemForm(x={}){return `<h2 id="modalTitle">${x.id?'Edit':'Add'} item</h2><p class="muted">Add directions, not sensitive information.</p><div class="form-grid fiveq-form"><div class="field"><label>Item name</label><input id="fTitle" value="${esc(x.title)}" placeholder="Home insurance"></div><div class="field"><label>Topic</label><select id="fDomain">${I.domains.map(d=>`<option ${x.domain===d?'selected':''}>${d}</option>`).join('')}</select></div><div class="field q-field"><label><span>1</span> Does it exist?</label><select id="fExists"><option value="unknown">Not sure</option><option value="yes" ${x.exists==='yes'?'selected':''}>Yes</option><option value="no" ${x.exists==='no'?'selected':''}>No or not needed</option></select></div><div class="field q-field"><label><span>2</span> Where is it?</label><input id="fLocation" value="${esc(x.location)}" placeholder="Blue folder in desk drawer"><small>Add a location hint.</small></div><div class="field q-field"><label><span>3</span> Who handles it?</label><input id="fHandler" value="${esc(x.handler)}" placeholder="Name or company"></div><div class="field q-field"><label><span>4</span> Who else knows?</label><input id="fKnows" value="${esc(x.whoKnows)}" placeholder="Name"><small>This can become a trusted contact in a future version.</small></div><div class="field"><label>Relationship</label><select id="fKnowsRelation"><option value="">Choose a relationship</option>${['Partner','Child','Parent','Sibling','Friend','Adviser','Other'].map(r=>`<option ${x.whoKnowsRelationship===r?'selected':''}>${r}</option>`).join('')}</select></div><div class="field q-field"><label><span>5</span> Last checked</label><input id="fConfirmed" type="date" value="${x.lastConfirmed?x.lastConfirmed.slice(0,10):''}"><small>Leave blank until you check it.</small></div><div class="field"><label>Check again in</label><select id="fOverdue"><option value="3" ${x.overdueMonths===3?'selected':''}>3 months</option><option value="6" ${x.overdueMonths===6?'selected':''}>6 months</option><option value="12" ${!x.overdueMonths||x.overdueMonths===12?'selected':''}>1 year</option></select></div><div class="field"><label><input id="fCritical" type="checkbox" ${x.critical?'checked':''}> Important for a handoff</label></div></div><div class="hero-actions"><button class="btn primary" type="button" id="saveItem">Save item</button>${x.id?'<button class="btn danger" type="button" id="deleteItem">Delete</button>':''}</div>`}
function editItem(id){let x=state.items.find(i=>i.id===id)||{};openModal(itemForm(x));document.querySelector('#saveItem').onclick=()=>{let title=document.querySelector('#fTitle').value.trim();if(!title)return toast('Enter an item name.');let obj={...x,id:x.id||crypto.randomUUID(),personId:x.personId||activePerson,title,domain:document.querySelector('#fDomain').value,exists:document.querySelector('#fExists').value,location:document.querySelector('#fLocation').value.trim(),handler:document.querySelector('#fHandler').value.trim(),whoKnows:document.querySelector('#fKnows').value.trim(),whoKnowsRelationship:document.querySelector('#fKnowsRelation').value,lastConfirmed:document.querySelector('#fConfirmed').value?new Date(document.querySelector('#fConfirmed').value+'T12:00:00').toISOString():null,overdueMonths:+document.querySelector('#fOverdue').value,critical:document.querySelector('#fCritical').checked,scenarioFlags:[]};let ix=state.items.findIndex(i=>i.id===obj.id);ix<0?state.items.push(obj):state.items[ix]=obj;save();closeModal();route='build';render();toast('Item saved.')};if(x.id)document.querySelector('#deleteItem').onclick=()=>{if(confirm('Delete this item?')){state.items=state.items.filter(i=>i.id!==x.id);save();closeModal();render()}}}
function editPerson(id){let p=person(id),self=p.id==='me';openModal(`<h2 id="modalTitle">Edit person</h2><div class="form-grid"><div class="field"><label>Name</label><input id="pName" value="${self?'':esc(p.name)}" placeholder="Real name"></div><div class="field"><label>Relationship</label><select id="pRelation" ${self?'disabled':''}>${(self?['Self']:['Partner','Child','Parent','Sibling','Friend','Other']).map(r=>`<option ${p.relationship===r?'selected':''}>${r}</option>`).join('')}</select></div></div><div class="hero-actions"><button type="button" class="btn primary" id="savePerson">Save</button></div>`);document.querySelector('#savePerson').onclick=()=>{let n=document.querySelector('#pName').value.trim();if(!n)return toast('Enter a real name.');p.name=self?'My map':n;if(!self)p.relationship=document.querySelector('#pRelation').value;save();closeModal();render()}}
function loadDemo(){if(state.items.length&&!confirm('Replace your current map with demo data?'))return;let d=n=>new Date(Date.now()-n*864e5).toISOString();state=blank();state.people[0].name='My map';state.people.push({id:'demo-child',name:'Maya Chen',relationship:'Child',trustedContacts:[]});let rows=[['Primary contact list','Contacts & Support','Hall cabinet','Jordan Lee','Maya Chen'],['Will and legal papers','Documents & Legal','Fireproof box','Harbor Legal','Jordan Lee'],['Monthly bills list','Money & Bills','Household binder','My map','Maya Chen'],['Home insurance','Insurance','Blue folder','Oak Insurance','Jordan Lee'],['Home shutoff notes','Home & Property','Utility cupboard','Jordan Lee','Maya Chen'],['Account recovery directions','Digital Life','Sealed note with lawyer','My map','Jordan Lee'],['Pet care plan','Family, Pets & Care','Kitchen notice board','Greenwood Vet','Maya Chen']];state.items=rows.map((r,i)=>({id:'demo-'+i,personId:'me',title:r[0],domain:r[1],exists:'yes',location:r[2],handler:r[3],whoKnows:r[4],whoKnowsRelationship:i%2?'Partner':'Child',lastConfirmed:d(i*35),overdueMonths:i%2?6:12,critical:true,scenarioFlags:[]}));save();toast('Demo map loaded.');render()}
function moreView(){return `<div class="page-head"><div><div class="eyebrow">Backup and print options</div><h1>Keep a copy of your map.</h1><p class="lead">Your map stays in this browser, but browser data can be cleared.</p></div></div><div class="more-grid"><section class="card"><h2>JSON backup</h2><p class="muted">Export a backup regularly. Importing a backup replaces the current map.</p><div class="hero-actions"><button class="btn" data-action="export">Export JSON</button><button class="btn" data-action="import">Import JSON</button></div></section><section class="card"><h2>Print or save a PDF</h2><p class="muted">Keep a paper copy or save a PDF from your browser.</p><button class="btn" data-action="print">Print / Save PDF</button></section><section class="card"><h2>Keep sensitive details elsewhere</h2><p class="muted">Backups and printed copies may contain names and location hints. Store them safely.</p></section><section class="card"><h2>Start over</h2><button class="btn danger" data-action="reset">Reset local data</button></section></div>`}
function addPerson(defaultRelation=''){openModal(`<h2 id="modalTitle">Add a person</h2><p class="muted">Use a real name and choose your relationship.</p><div class="form-grid"><div class="field"><label>Name</label><input id="pName" placeholder="Real name"></div><div class="field"><label>Relationship</label><select id="pRelation">${['Partner','Child','Parent','Sibling','Friend','Other'].map(r=>`<option ${defaultRelation===r?'selected':''}>${r}</option>`).join('')}</select></div></div><button type="button" class="btn primary" id="savePerson">Add person</button>`);document.querySelector('#savePerson').onclick=()=>{let n=document.querySelector('#pName').value.trim();if(!n)return toast('Enter a real name.');let p={id:crypto.randomUUID(),name:n,relationship:document.querySelector('#pRelation').value,trustedContacts:[]};state.people.push(p);activePerson=p.id;save();closeModal();route='build';render();toast('Person added.')}}
document.querySelector('#importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let reader=new FileReader();reader.onload=()=>{try{let x=JSON.parse(reader.result);if(!Array.isArray(x.people)||!Array.isArray(x.items))throw Error();x.people=x.people.map((p,i)=>({...p,name:p.id==='me'||(!i&&p.relationship==='Self')?'My map':p.name}));x.items=x.items.map(i=>({...i,domain:V2_MOVE[i.domain]||i.domain,scenarioFlags:[]}));if(confirm('Replace the current map with this backup?')){state=x;save();render();toast('Backup imported.')}}catch{toast('That file is not a valid Be Prepared backup.')}};reader.readAsText(f);e.target.value=''};
render();
